apiVersion: v1
kind: Namespace
metadata:
  name: istio-demo
  labels:
    istio-injection: enabled
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: istio-demo
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: user
  namespace: istio-demo
spec:
  selector:
    matchLabels:
      app: user
  portLevelMtls:
    8080:
      mode: PERMISSIVE
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: demo-gateway
  namespace: istio-demo
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - 'api.istio.demo'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - 'api.istio.demo'
    port:
      name: api
      number: 443
      # NOTE: this port serves both HTTP and gPRC(HTTP/2) traffic.
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
---
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: istio-demo
  namespace: istio-demo
spec:
  egress:
  - hosts:
    - "./*"
    - "istio-system/*"
  outboundTrafficPolicy:
    # NOTE: the default mode is ALLOW_ANY (v1.4.3) 
    # defined in configmap istio in istio-system namespace.
    mode: REGISTRY_ONLY
---
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: accounts
  namespace: istio-demo
spec:
  workloadSelector:
    labels:
      app: account
  egress:
  - hosts:
    - "./user.istio-demo.svc.cluster.local"
    - "./auth.istio-demo.svc.cluster.local"
    - "istio-system/*"
---
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: users
  namespace: istio-demo
spec:
  workloadSelector:
    labels:
      app: user
  egress:
  - hosts:
    - "mongo/mongo-mongodb.mongo.svc.cluster.local"
    - "istio-system/*"
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
---
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: auths
  namespace: istio-demo
spec:
  workloadSelector:
    labels:
      app: auth
  egress:
  - hosts:
    - "redis/redis-server.redis.svc.cluster.local"
    - "istio-system/*"
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: accounts
  namespace: istio-demo
spec:
  gateways:
  - demo-gateway
  - mesh # also apply to sidecars in the mesh.
  hosts:
  - api.istio.demo
  - account.istio-demo.svc.cluster.local
  http: 
  - name: account-http
    match:
    - name: match-header
      uri:
        prefix: /v1/accounts
      headers:
        uid:
          exact: gerry
    route:
    - destination:
        host: account.istio-demo.svc.cluster.local
        port: 
          number: 8080
        subset: v011
    timeout: 5s
  - name: account-http
    match:
    - name: default
      uri:
        prefix: /v1/accounts
    route:
    - destination:
        host: account.istio-demo.svc.cluster.local
        port: 
          number: 8080
        subset: v010
      weight: 50
    - destination:
        host: account.istio-demo.svc.cluster.local
        port: 
          number: 8080
        subset: v011
      weight: 50
  - name: account-grpc
    match:
    - uri:
        prefix: /api.Account
    - uri:
        prefix: /grpc.reflection
    route:
    - destination:
        host: account.istio-demo.svc.cluster.local
        port: 
          number: 8000
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: accounts
  namespace: istio-demo
spec:
  host: account.istio-demo.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v010
    labels:
      version: v0.1.0
  - name: v011
    labels:
      version: v0.1.1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: users
  namespace: istio-demo
spec:
  hosts:
  - user.istio-demo.svc.cluster.local
  http: 
  - route:
    - destination:
        host: user.istio-demo.svc.cluster.local
        port:
          number: 8000
        subset: v010
      weight: 100
    - destination:
        host: user.istio-demo.svc.cluster.local
        port:
          number: 8000
        subset: v011
      weight: 0
    mirror:
      host: user.istio-demo.svc.cluster.local
      port:
        number: 8000
      subset: v010
    mirrorPercentage:
      value: 100.0
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: users
  namespace: istio-demo
spec:
  host: user.istio-demo.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v010
    labels:
      version: v0.1.0
  - name: v011
    labels:
      version: v0.1.1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: auths
  namespace: istio-demo
spec:
  hosts:
  - auth.istio-demo.svc.cluster.local
  http: 
  - name: auth-grpc
    match:
    - uri:
        prefix: /api.Auth
    route:
    - destination:
        host: auth.istio-demo.svc.cluster.local
        port: 
          number: 8000
        subset: v010
    fault:
      delay:
        # NOTE: the percentage is needed, at least for the version v1.4.3 I tested against, 
        # or it will assume its value is 0, means no requests will be applied.
        percentage: 
          value: 0 
        fixedDelay: 3s
      abort:
        percentage:
          value: 0
        httpStatus: 400
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: auths
  namespace: istio-demo
spec:
  host: auth.istio-demo.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v010
    labels:
      version: v0.1.0
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mongodb
  namespace: istio-demo
spec:
  hosts:
  - mongo-mongodb.mongo.svc.cluster.local
  tcp:
  - match:
    - port: 27017
    route:
    - destination:
        host: mongo-mongodb.mongo.svc.cluster.local
        port:
          number: 27017
