apiVersion: v1
kind: Namespace
metadata:
  name: istio-demo
  labels:
    istio-injection: enabled
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: demo-gateway
  namespace: istio-demo
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - 'api.istio.demo'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - 'api.istio.demo'
    port:
      name: api
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: accounts
  namespace: istio-demo
spec:
  gateways:
  - demo-gateway
  hosts:
  - api.istio.demo
  http: 
  - name: account-http
    match:
    - name: match-header
      uri:
        prefix: /v1/accounts
      headers:
        uid:
          exact: gerry
    route:
    - destination:
        host: account.istio-demo.svc.cluster.local
        port: 
          number: 8080
        subset: v011
    timeout: 5s
  - name: account-http
    match:
    - name: default
      uri:
        prefix: /v1/accounts
    route:
    - destination:
        host: account.istio-demo.svc.cluster.local
        port: 
          number: 8080
        subset: v010
      weight: 50
    - destination:
        host: account.istio-demo.svc.cluster.local
        port: 
          number: 8080
        subset: v011
      weight: 50
  - name: account-grpc
    match:
    - uri:
        prefix: /api.Account
    - uri:
        prefix: /grpc.reflection
    route:
    - destination:
        host: account.istio-demo.svc.cluster.local
        port: 
          number: 8000
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: accounts
  namespace: istio-demo
spec:
  host: account.istio-demo.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v010
    labels:
      version: v0.1.0
  - name: v011
    labels:
      version: v0.1.1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: users
  namespace: istio-demo
spec:
  hosts:
  - user.istio-demo.svc.cluster.local
  http: 
  - route:
    - destination:
        host: user.istio-demo.svc.cluster.local
        subset: v010
      weight: 100
    - destination:
        host: user.istio-demo.svc.cluster.local
        subset: v011
      weight: 0
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: users
  namespace: istio-demo
spec:
  host: user.istio-demo.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v010
    labels:
      version: v0.1.0
  - name: v011
    labels:
      version: v0.1.1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: auths
  namespace: istio-demo
spec:
  hosts:
  - auth.istio-demo.svc.cluster.local
  http: 
  - name: auth-grpc
    match:
    - uri:
        prefix: /api.Auth
    route:
    - destination:
        host: auth.istio-demo.svc.cluster.local
        port: 
          number: 8000
        subset: v010
    fault:
      delay:
        # NOTE: the percentage is needed, at least for the version v1.4.3 I tested against, 
        # or it will assume its value is 0, means no requests will be applied.
        percentage: 
          value: 0 
        fixedDelay: 3s
      abort:
        percentage:
          value: 0
        httpStatus: 400
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: auths
  namespace: istio-demo
spec:
  host: auth.istio-demo.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v010
    labels:
      version: v0.1.0
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: redis-master
  namespace: istio-demo
spec:
  hosts:
  - redis5-master.redis.svc.cluster.local
  tcp:
  - match:
    - port: 6379
    route:
    - destination:
        host: redis5-master.redis.svc.cluster.local
        port:
          number: 6379
