apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth
  namespace: istio-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-v0.1.0
  namespace: istio-demo
  labels:
    app: auth
    version: v0.1.0
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: auth
      version: v0.1.0
  template:
    metadata:
      name: auth
      labels:
        app: auth
        version: v0.1.0
    spec:
      serviceAccountName: auth
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: auth-grpc
        image: ginuerzh/auth-svc:0.1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: GRPC_ADDR
          value: ":8000"
        - name: REDIS_URL
          value: "redis://redis-server.redis.svc.cluster.local:6379"
        - name: TTL
          value: "300s"
        volumeMounts:
        - name: rsa-key
          mountPath: /ssl/
          readOnly: true
        ports:
        - name: grpc
          containerPort: 8000
          protocol: TCP
        readinessProbe:
          periodSeconds: 10
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8000"]
        livenessProbe:
          periodSeconds: 10
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8000"]
      volumes:
      - name: rsa-key
        secret:
          secretName: auth-rsa-key
          optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: istio-demo
spec:
  selector:
    app: auth
  ports:
  - name: grpc
    port: 8000
    targetPort: grpc
